captcha:
  key: ""
  provider: "capsolver.com" # Or capmonster.cloud, more soon
  site key: "4c672d35-0701-42b2-88c3-78380b0db560" # Changes 1-2 times a year

settings:
  rotating proxy: "" # username:password@host:port
  discord build number: "" # leave empty to automate

token:
  username: "" # Leave empty for random
