captcha:
  key: "CAP-51547E428B55710DF18681B9306F3F2A"
  provider: "capsolver.com" # Or capmonster.cloud, more soon
  site key: "4c672d35-0701-42b2-88c3-78380b0db560" # Changes 1-2 times a year

settings:
  discord build number: "30" # leave empty to automate

token:
  username: "" # Leave empty for random
