captcha:
  key: "CAP-9E67230CD9A5B7E5B5EE1311AF1EC84A"
  provider: "capsolver.com" # Or capmonster.cloud, more soon
  site key: "4c672d35-0701-42b2-88c3-78380b0db560" # Changes 1-2 times a year

settings:
  discord build number: "30" # leave empty to automate

token:
  username: "" # Leave empty for random
